---
title: "More on data science, data and our purposes"
subtitle: ""
author: "Conan Liu"
date: "30 July 2021"
output:
  ioslides_presentation:
    css: slides.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Problem identification

We must outline objectives for the project 

These will be translated into problems which will be solved using data science

These problems must be well understood

For example: what users spend the most time on Instagram and why?
* you aim to find areas where you can make an impact, and improve user efficiency

## Preprocessing

Preprocessing prepares the dataset (broadly in data science, data is often unstructured and not ideal) for both exploratory data analysis and modelling

May include missing value treatment for example

## EDA

Utilises data visualisation and other methods to extract insightful information from the dataset

Aids modelling processes, for example:
identifying the important variables
uncovering relationships between variables

## Further preprocessing

Outliers are removed

Feature engineering (modifying existing variables, for example, or creating new ones)

Dataset must be split into training and testing components

## Modelling

Applicable models must be chosen and implemented

Models must be:
* Trained on training data
* Tuned (parameters must be optimised)
* Tested on test data (form predictions with test data)

## Evaluation and feedback

Models are evaluated and compared against a specified metric(s)

Suitability for the task is determined

Optimal model for the task is identified

We reflect on our processes and look to improve 


